<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MoveCommand" Id="{965c49e3-202e-4ced-98b3-f8f941c0dc3b}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK ABSTRACT MoveCommand EXTENDS Command IMPLEMENTS I_MoveCommand
VAR
	_axisRef : REFERENCE TO Axis;
	_velocity : LREAL;
	_acceleration: LREAL;
	_deceleration: LREAL;
	_jerk: LREAL;
	_bufferMode: AxisBufferMode;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MoveCommand">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>